[package]
name = "wafflecord"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
chrono = "0.4.39"
poise = "0.6.1"
serde = "1.0.217"
sled = "0.34.7"
tokio = { version = "1.43.0", features = ["full"] }
tokio_schedule = "0.3.2"
